### ISSUE TITLE
when I run the matlab demo, the loss is very large more than 60,000,000

### ISSUE THREAD

**Issue by ssll2999** [jiangqy/DCMH-CVPR2017#1]
Is that normal？

**Comment by jiangqy** [comment]
This loss is calculated based on all training samples. Hence it's very large. @ssll2999 
The following figure shows the loss on MIRFLICKR-25K.

![loss](https://user-images.githubusercontent.com/14566109/29956054-fdca61b0-8f16-11e7-8e88-356811d351bf.jpg)

**Comment by ssll2999** [comment]
Thanks @jiangqy , is this the loss curve of the matlab demo? My loss is still much larger than yours on the same dataset.

**Comment by jiangqy** [comment]
Yes.  How many data points do you use for  training?
My loss is shown as follows (10000 data points for training):
#16 bits
69382238.892
69556266.941
69565961.230
69546562.942
...
#32 bits
69423970.282
69809313.352
69814847.011
69799314.250
...
#64 bits
69468403.462
70270757.003
70321007.783
70292580.244
...
@ssll2999

**Comment by ssll2999** [comment]
I use 10000 data points  for training too, and the loss you show above is similar with mine. Thank you very much! @jiangqy

**Comment by ssll2999** [comment]
I'd like to train on the IAPR TC-12 and NUS-WIDE dataset to see the performan . Could you share the two dataset or the methods to generate, please?@jiangqy, thankyou very much!

**Comment by jiangqy** [comment]
Please leaving your email address and I will provided the pre-processed dataset files for IAPR-TC12 and NUS-WIDE. @ssll2999

**Comment by jiangqy** [comment]
Please leaving your email address and I will provide the pre-processed dataset files for IAPR-TC12 and NUS-WIDE. @ssll2999

**Comment by jiangqy** [comment]
Please leave your email address and I will provide the pre-processed dataset files for IAPR-TC12 and NUS-WIDE. @ssll2999

**Comment by ssll2999** [comment]
ssll2999@163.com, many  thanks!@jiangqy
