### ISSUE TITLE
magic of data sampling

### ISSUE THREAD

**Issue by iTomxy** [jiangqy/DCMH-CVPR2017#13]
I found that the model fails to re-produce the results when using the commented-out sampling strategy in [Ln 37](https://github.com/jiangqy/DCMH-CVPR2017/blob/master/DCMH_tensorflow/DCMH_tensorflow/DCMH_demo.py#L37) and [Ln 41](https://github.com/jiangqy/DCMH-CVPR2017/blob/master/DCMH_tensorflow/DCMH_tensorflow/DCMH_demo.py#L41) in *DCMH_demo.py*, i.e., *sampling WITHOUT replacement*, even if I shuffle the `index` before each training epochs. And it works well with Ln 39 ~ 40, i.e.,  *sampling WITH replacement*.
But why ?

**Comment by jiangqy** [comment]
The expectations of the gradient are the same for these two settings.
