### ISSUE TITLE
classes order & name of NUS-WIDE

### ISSUE THREAD

**Issue by iTomxy** [jiangqy/DCMH-CVPR2017#14]
Hi, I wonder the classes order of the label vector and their corresponding class name of the NUS-WIDE data provided in [DCMH-CVPR2017/DCMH_tensorflow/DCMH_tensorflow/readme.txt](https://github.com/jiangqy/DCMH-CVPR2017/blob/master/DCMH_tensorflow/DCMH_tensorflow/readme.txt).
Or can you provided the processing code of NUS-WIDE ?
thanks

**Comment by jiangqy** [comment]
Sorry, I have graduated. If you need the classes order, you may need to preprocess the data by yourself.
