### ISSUE TITLE
mismatch with imagenet-vgg-f.mat

### ISSUE THREAD

**Issue by prraoo** [jiangqy/DCMH-CVPR2017#4]
Hi @jiangqy ,

Thanks for the code.  I have a small request, is it possible to share the **image net mat** file you used in this work? 
I think the mat file from here http://www.vlfeat.org/matconvnet/pretrained/ looks different form what you have used. 

Thank you.

**Comment by jiangqy** [comment]
http://lamda.nju.edu.cn/jiangqy/data/DCMH_data/data.zip

**Comment by ZiTian8** [comment]
你好，蒋博士，请问下tensorflow版本代码使用的也是vgg_net.mat文件吗

**Comment by jiangqy** [comment]
是的。 @ZiTian8

**Comment by liu-hx** [comment]
你好，蒋博士，你上面分享的获取 imagenet-vgg-f.mat的链接好像失效了，可以在发一个链接吗？谢谢。

**Comment by jiangqy** [comment]
http://lamda.nju.edu.cn/jiangqy/data/DCMH_data/vgg-net.zip @Lliuhaoxin

**Comment by xunguangwang** [comment]
https://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-f.mat

**Comment by jiangqy** [comment]
http://www.lamda.nju.edu.cn/jiangqy/data/DCMH_data/vgg-net.zip @xunguangwang

**Comment by zjjjjjjj2017** [comment]
您好，您上面分享的vgg_net.zip链接失效了，请问可以再发一遍吗？谢谢。

**Comment by ArtyZe** [comment]
@jiangqy @xunguangwang @liu-hx @ZiTian8 @prraoo Hello, I meet same error right now, could you please share me the right imagenet-vgg-f.mat file? Thanks

**Comment by prraoo** [comment]
@ArtyZe I manually fixed few keys after the loading mat file. Take one of the files given above and fix it. Sorry could not help you much here.
