### ISSUE TITLE
求数据集合并方法或下载地址

### ISSUE THREAD

**Issue by limycml** [jiangqy/DCMH-CVPR2017#6]
你提供了MIRFLICKR25K、NUS-WIDE的下载地址，并说明了将多个文件合并为一个文件，
请问问合并文件的方法可以提供吗？或者直接提供合并后的文件链接也可以，万分感谢。

另：IAPR TC-12 这个数据集可以提供下载地址嘛？

**Comment by Sisi0518** [comment]
你好，我也没有找到数据合并的方法，请问你找到了吗？

**Comment by broliang** [comment]
数据集合并了也有问题啊。

**Comment by broliang** [comment]
我读数据时直接提示OSError: Unable to open file (file signature not found)，各位大佬怎么解决

**Comment by jiangqy** [comment]
合并方法：以FLICKR-25K为例：
`
function merge_data_example()
load mirflickr25k-iall.mat IAll;
load mirflickr25k-lall.mat LAll;
load mirflickr25k-yall.mat YAll;
images = IAll;
clear IAll;
save FLICKR-25K.mat YAll LAll images -v7.3; 
end
`
@limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
@broliang matlab报错还是python报错？

**Comment by jiangqy** [comment]
合并方法：以FLICKR-25K为例：
`
function merge_data_example() 

load mirflickr25k-iall.mat IAll; 

load mirflickr25k-lall.mat LAll; 

load mirflickr25k-yall.mat YAll; 

images = IAll; 

clear IAll; 

save FLICKR-25K.mat YAll LAll images -v7.3; 

end
`
@limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
@broliang matlab报错还是python报错？

**Comment by broliang** [comment]
python报错
lall = h5py.File('F:\博士\personsearch\SSAH\data\mirflickr25k-lall.mat')
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)





------------------ 原始邮件 ------------------
发件人: "Jiang. Qing-Yuan"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 中午11:11
收件人: "jiangqy/DCMH-CVPR2017"<DCMH-CVPR2017@noreply.github.com>; 
抄送: "happy live"<382281216@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiangqy/DCMH-CVPR2017] 求数据集合并方法或下载地址 (#6)




合并方法：以FLICKR-25K为例：
 function merge_data_example() load mirflickr25k-iall.mat IAll; load mirflickr25k-lall.mat LAll; load mirflickr25k-yall.mat YAll; images = IAll; clear IAll; save FLICKR-25K.mat YAll LAll images -v7.3;  end
 @limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
 @broliang matlab报错还是python报错？

**Comment by jiangqy** [comment]
合并方法：以FLICKR-25K为例：
`
function merge_data_example() 
load mirflickr25k-iall.mat IAll; 
load mirflickr25k-lall.mat LAll; 
load mirflickr25k-yall.mat YAll;
images = IAll; 
clear IAll; 
save FLICKR-25K.mat YAll LAll images -v7.3; 
end
`
@limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
@broliang matlab报错还是python报错？

**Comment by jiangqy** [comment]
合并方法：以FLICKR-25K为例：
% matlab code
% -------------------------------
function merge_data_example() 
load mirflickr25k-iall.mat IAll; 
load mirflickr25k-lall.mat LAll; 
load mirflickr25k-yall.mat YAll; 
images = IAll; 
clear IAll; 
save FLICKR-25K.mat YAll LAll images -v7.3; 
end
% -------------------------------
@limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
@broliang matlab报错还是python报错？

**Comment by limycml** [comment]
非常感谢你的细心答复，FLICKR-25K我已经解决了，能提供NUSWIDE的数据集或者合并方法嘛？
 
------------------
Best regards.
Mingyong.    donghua university


 




------------------ 原始邮件 ------------------
发件人: "Jiang. Qing-Yuan"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 中午11:13
收件人: "jiangqy/DCMH-CVPR2017"<DCMH-CVPR2017@noreply.github.com>; 
抄送: "木头"<41560739@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiangqy/DCMH-CVPR2017] 求数据集合并方法或下载地址 (#6)




合并方法：以FLICKR-25K为例：
 function merge_data_example()  load mirflickr25k-iall.mat IAll;  load mirflickr25k-lall.mat LAll;  load mirflickr25k-yall.mat YAll; images = IAll;  clear IAll;  save FLICKR-25K.mat YAll LAll images -v7.3;  end
 @limycml IAPR-TC12请自行处理，因服务器迁移，最早用于实验的数据集已经找不到了。
 @broliang matlab报错还是python报错？

**Comment by jiangqy** [comment]
@broliang python合并也可以，可以试试scipy.io接口读取.mat。或者你改一下加载的地方，就不必合并再存一遍了

**Comment by broliang** [comment]
ok，谢谢啦




------------------ 原始邮件 ------------------
发件人: "Jiang. Qing-Yuan"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 中午11:16
收件人: "jiangqy/DCMH-CVPR2017"<DCMH-CVPR2017@noreply.github.com>; 
抄送: "happy live"<382281216@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jiangqy/DCMH-CVPR2017] 求数据集合并方法或下载地址 (#6)




@broliang python合并也可以，可以试试scipy.io接口读取.mat。或者你改一下加载的地方，就不必合并再存一遍了

**Comment by jiangqy** [comment]
@limycml 三个数据集合并方法都是一样的，主要是NUS-WIDE太大了，下载解压（20-30G）。也可以用类似上述格式合并，或者改一下读取接口即可。

**Comment by limycml** [comment]
OK，谢谢啦。
