### ISSUE TITLE
details of partition of NUS-WIDE

### ISSUE THREAD

**Issue by iTomxy** [jiangqy/DCMH-CVPR2017#8]
hello, I'm asking a details of the partition of the NUS-WIDE data set.
before that, did you follow the settings like **randomly select XXX samples in each classes for query set**? if yes, then my question is:
how do you randomly select 100 samples in each classes for the query set (and so does the training set)?
I mean, as it's a multi-label data set, a same very sample might be selected several times during the sampling of each classes.
thanks

**Comment by jiangqy** [comment]
In this work, we only randomly select 2100 data points to construct the query set.

However, in our other works, e.g., ADSH, we randomly select 2100 data points (100 images per class). I understand your problem. I think this splitting strategy is slightly ambiguous, but I also have to follow the setting of previous works. And my understanding is we randomly sample 2100 data points and *ensure* that each class contains at least 100 images. That is to say, the randomness of sampling is defined over per class, not all classes. 

> hello, I'm asking a details of the partition of the NUS-WIDE data set.
> before that, did you follow the settings like **randomly select XXX samples in each classes for query set**? if yes, then my question is:
> how do you randomly select 100 samples in each classes for the query set (and so does the training set)?
> I mean, as it's a multi-label data set, a same very sample might be selected several times during the sampling of each classes.
> thanks
