### ISSUE TITLE
image conversion

### ISSUE THREAD

**Issue by LiqiangJing** [jiangqy/DCMH-CVPR2017#9]
Hi! I want to know how the original image from flickr25k convert to 3*224*224 matrix, because I have want to convert matrix to image.

**Comment by long123long** [comment]
you can get the image of the numpy array, just transpose it.
And I want to know how to match the word with the BOW?

**Comment by LiqiangJing** [comment]
Oh! Thanks. I have solved my problem.

**Comment by long123long** [comment]
Do you know how to get the word realation about BOW?

**Comment by long123long** [comment]
Can I get your QQ number about some question？

**Comment by LiqiangJing** [comment]
my qq is 577279815

**Comment by long123long** [comment]
Thanks.
